alter table jobs add column if not exists id_verification_token uuid not null default gen_random_uuid();
alter table jobs add column if not exists id_verification_completed_at timestamptz;
alter table jobs add column if not exists id_verification_face_path text;
alter table jobs add column if not exists id_verification_license_path text;
alter table jobs add column if not exists id_verification_sent_at timestamptz;

create unique index if not exists jobs_id_verification_token_idx on jobs(id_verification_token);

-- Private bucket — never public. Only accessed via signed URLs generated by
-- authenticated admin/dealer users, and written to only by the service-role
-- server route (never directly by the anonymous customer or the driver).
insert into storage.buckets (id, name, public)
values ('id-verification', 'id-verification', false)
on conflict (id) do nothing;

-- Only platform admin, or the org admin of the dealer who owns the job, can ever
-- view these photos — drivers are deliberately excluded, matching the requirement
-- that they see completion status only, never the actual ID/face images.
drop policy if exists "id verification viewable by admin and owning dealer" on storage.objects;
create policy "id verification viewable by admin and owning dealer" on storage.objects
for select using (
  bucket_id = 'id-verification'
  and (
    exists (select 1 from profiles where id = auth.uid() and role = 'platform_admin')
    or exists (
      select 1 from jobs j
      join profiles p on p.organization_id = j.organization_id
      where p.id = auth.uid() and p.role = 'org_admin'
        and (storage.foldername(storage.objects.name))[1] = j.id::text
    )
  )
);

-- Public (token-gated) read access for the verification page itself, and to let
-- the customer submit their photos without needing an authenticated account.
drop function if exists get_verification_info(uuid);
create or replace function get_verification_info(p_token uuid)
returns table (
  job_id uuid,
  customer_full_name text,
  vehicle_year int,
  vehicle_make text,
  vehicle_model text,
  driver_name text,
  status text,
  id_verification_completed_at timestamptz,
  organization_phone text,
  organization_name text
)
language sql
security definer
stable
as $$
  select j.id, j.customer_full_name, j.vehicle_year, j.vehicle_make, j.vehicle_model,
         p.full_name, j.status, j.id_verification_completed_at, o.phone, o.name
  from jobs j
  left join profiles p on p.id = j.driver_id
  left join organizations o on o.id = j.organization_id
  where j.id_verification_token = p_token;
$$;
grant execute on function get_verification_info(uuid) to anon, authenticated;

create or replace function submit_id_verification(p_token uuid, p_face_path text, p_license_path text)
returns boolean
language plpgsql
security definer
as $$
begin
  update jobs
  set id_verification_face_path = p_face_path,
      id_verification_license_path = p_license_path,
      id_verification_completed_at = now()
  where id_verification_token = p_token;

  update job_checklist_items
  set completed_at = now()
  where item_type = 'customer_id_verification'
    and job_id = (select id from jobs where id_verification_token = p_token);

  return found;
end;
$$;
grant execute on function submit_id_verification(uuid, text, text) to anon, authenticated;
